function [allData, scenario, sensor] = mi_mariposa()
%drivinmariposa - Returns sensor detections
%    allData = drivinmariposa returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = drivinmariposa optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 28-Apr-2026 13:27:00

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
sensor = createSensor(scenario);

% Add sensor to scenario
addSensors(scenario, sensor, egoVehicle.ActorID);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    time  = scenario.SimulationTime;

    if ~isa(sensor,'insSensor')
        poses = targetPoses(scenario,sensor.SensorIndex);
    end
    % Generate detections for the sensor
    laneDetections = [];
    ptClouds = [];
    insMeas = [];
    [objectDetections, isValidTime] = sensor(poses, time);
    numObjects = length(objectDetections);
    objectDetections = objectDetections(1:numObjects);

    % Aggregate all detections into a structure for later use
    %if isValidTime
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    %end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release the sensor object so it can be used again.
release(sensor);

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function sensor = createSensor(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensor = visionDetectionGenerator('SensorIndex', 1, ...
    'SensorLocation', [0.12 0], ...
    'MaxRange', 100, ...
    'DetectorOutput', 'Objects only', ...
    'Intrinsics', cameraIntrinsics([1814.81 1814.81],[320 240],[480 640]), ...
    'ActorProfiles', profiles);

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-2.035 -0.354 0;
    2.038 -0.37 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Length', 0.24, ...
    'Width', 0.19, ...
    'Height', 0.1, ...
    'Position', [0 0 0.01], ...
    'RearOverhang', 0.03, ...
    'FrontOverhang', 0.03, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [0 0 0.01;
    0.284 -0.081 0.01;
    0.522 -0.175 0.01;
    0.777 -0.361 0.01;
    1.031 -0.633 0.01;
    1.235 -0.862 0.01;
    1.439 -1.176 0.01;
    1.524 -1.465 0.01;
    1.464 -1.839 0.01;
    1.244 -1.941 0.01;
    0.946 -1.975 0.01;
    0.709 -1.873 0.01;
    0.564 -1.703 0.01;
    0.386 -1.465 0.01;
    0.216 -1.193 0.01;
    0.063 -0.888 0.01;
    -0.072 -0.616 0.01;
    -0.191 -0.361 0.01;
    -0.336 -0.022 0.01;
    -0.471 0.335 0.01;
    -0.599 0.742 0.01;
    -0.743 1.082 0.01;
    -0.947 1.438 0.01;
    -1.227 1.685 0.01;
    -1.567 1.778 0.01;
    -1.855 1.693 0.01;
    -1.94 1.345 0.01;
    -1.804 1.014 0.01;
    -1.618 0.87 0.01;
    -1.346 0.666 0.01;
    -1.091 0.42 0.01;
    -0.82 0.148 0.01;
    -0.531 -0.081 0.01;
    -0.242 -0.09 0.01;
    0.013 -0.039 0.01;
    0.284 0.063 0.01;
    0.539 0.182 0.01;
    0.726 0.318 0.01;
    0.912 0.505 0.01;
    1.082 0.776 0.01;
    1.252 1.048 0.01;
    1.354 1.269 0.01;
    1.329 1.574 0.01;
    1.176 1.846 0.01;
    0.819 1.863 0.01;
    0.505 1.77 0.01;
    0.293 1.549 0.01;
    0.165 1.277 0.01;
    0.063 0.989 0.01;
    -0.055 0.632 0.01;
    -0.183 0.275 0.01;
    -0.31 -0.073 0.01;
    -0.42 -0.446 0.01;
    -0.565 -0.811 0.01;
    -0.701 -1.202 0.01;
    -0.853 -1.508 0.01;
    -1.066 -1.856 0.01;
    -1.337 -2.042 0.01;
    -1.601 -2.119 0.01;
    -1.864 -2.009 0.01;
    -1.957 -1.83 0.01;
    -1.94 -1.474 0.01;
    -1.787 -1.227 0.01;
    -1.575 -1.075 0.01;
    -1.312 -0.922 0.01;
    -1.074 -0.718 0.01;
    -0.904 -0.565 0.01;
    -0.726 -0.412 0.01;
    -0.531 -0.226 0.01;
    -0.344 -0.107 0.01;
    -0.106 -0.056 0.01;
    0.097 -0.056 0.01];
speed = [0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15;0.15];
trajectory(egoVehicle, waypoints, speed);

